# Generated by Django 3.1.3 on 2020-11-28 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestingSolution',
        ),
    ]
