# Generated by Django 3.1.3 on 2020-11-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testingsolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='type',
            field=models.IntegerField(choices=[(0, 'Код'), (1, 'Текст'), (2, 'Творческая')], default=0),
        ),
    ]
