# Generated by Django 3.1.3 on 2020-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingsolution',
            name='type',
            field=models.IntegerField(choices=[(0, 'Отклонено'), (1, 'Новое'), (2, 'Подтверждено')], default=1),
        ),
    ]
