# Generated by Django 3.1.3 on 2020-11-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_testingsolution_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testingsolution',
            old_name='type',
            new_name='status',
        ),
    ]
