# Generated by Django 3.1.3 on 2020-11-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20201128_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
