# Generated by Django 3.1.3 on 2020-11-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_testing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingsolution',
            name='reviewer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
