# Generated by Django 3.1.3 on 2020-11-27 17:37

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201127_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dutie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Обязанность', max_length=200, null=True)),
                ('created', models.DateTimeField(default=crm.models.default_time)),
            ],
        ),
        migrations.CreateModel(
            name='Сondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Условие', max_length=200, null=True)),
                ('created', models.DateTimeField(default=crm.models.default_time)),
            ],
        ),
    ]
