# Generated by Django 3.1.3 on 2020-11-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_dutie_сondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dutie',
            new_name='Duty',
        ),
    ]
