# Generated by Django 3.1.3 on 2020-11-27 18:21

import crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20201127_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Сайт'), (1, 'HeadHunter'), (2, 'SuperJob')], default=0)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='')),
                ('cv_recognition', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=crm.models.default_time)),
                ('core_condidate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='condidate_applicatin', to='crm.candidate')),
                ('core_vacancy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applicatin', to='crm.vacancy')),
            ],
        ),
    ]
