# Generated by Django 3.1.3 on 2020-11-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20201128_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.IntegerField(choices=[(0, 'Любой'), (1, 'Москва'), (2, 'Калининград'), (3, 'Казань'), (4, 'Санкт-Петербург'), (5, 'Краснодар')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новая'), (1, 'В работе'), (100, 'Закрыта')], default=0, null=True),
        ),
    ]
