# Generated by Django 3.1.3 on 2020-11-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_testing_testingsolution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
        migrations.DeleteModel(
            name='TestingSolution',
        ),
    ]
