# Generated by Django 3.1.3 on 2020-11-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testingsolution'),
        ('crm', '0016_vacancy_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='testing_solution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_test', to='tests.testingsolution'),
        ),
    ]
