# Generated by Django 3.1.3 on 2020-11-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_candidateapplication_testing_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='additional_skills_conformity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='key_skills_conformity',
            field=models.IntegerField(default=0),
        ),
    ]
