# Generated by Django 3.1.3 on 2020-11-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_auto_20201128_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='status',
            field=models.IntegerField(choices=[(0, 'Отказ'), (1, 'Новая'), (2, 'Собеседование'), (3, 'Служба безопасности'), (4, 'Оффер')], default=1),
        ),
    ]
